"""Baseline events

Revision ID: 68618049950a
Revises: e6f7a8b9c0d1
Create Date: 2026-06-10 00:57:20.780375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68618049950a'
down_revision: Union[str, None] = 'e6f7a8b9c0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_event',
    sa.Column('label', sa.String(length=100), nullable=True, comment='Free-text label, e.g. design-freeze'),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('signed_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signed_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baseline_event_item',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['baseline_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baseline_event_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_event_item_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_baseline_event_item_requirement_id'), ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baseline_event_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_event_item_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_baseline_event_item_event_id'))

    op.drop_table('baseline_event_item')
    op.drop_table('baseline_event')
    # ### end Alembic commands ###
