"""Requirement staleness flag

Revision ID: 9ff91c5a4252
Revises: 68618049950a
Create Date: 2026-06-10 01:05:15.909834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff91c5a4252'
down_revision: Union[str, None] = '68618049950a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stale', sa.Boolean(), nullable=False, server_default=sa.false(), comment='Parent was revised after this row last got a fresh look'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.drop_column('stale')

    # ### end Alembic commands ###
