"""Add kind column to attachment

Revision ID: a310ab9da1d8
Revises: eb217417d6d2
Create Date: 2026-05-17 06:22:33.821880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a310ab9da1d8'
down_revision: Union[str, None] = 'eb217417d6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), nullable=True, comment="'inline' = embedded in markdown content; 'reference' = downloadable doc; null = legacy/unscoped"))
        batch_op.create_index(batch_op.f('ix_attachment_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_kind'))
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
