"""Add step_dependency table for operation-level gating

Revision ID: bb285af00e88
Revises: 00d3ac121e5e
Create Date: 2026-05-17 04:51:50.070485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb285af00e88'
down_revision: Union[str, None] = '00d3ac121e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_dependency',
    sa.Column('step_id', sa.Integer(), nullable=False, comment='The dependent (gated) step'),
    sa.Column('depends_on_step_id', sa.Integer(), nullable=False, comment='The prerequisite step'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['procedure_step.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['procedure_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'depends_on_step_id', name='uq_step_dependency')
    )
    with op.batch_alter_table('step_dependency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_dependency_depends_on_step_id'), ['depends_on_step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_dependency_step_id'), ['step_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_dependency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_dependency_step_id'))
        batch_op.drop_index(batch_op.f('ix_step_dependency_depends_on_step_id'))

    op.drop_table('step_dependency')
    # ### end Alembic commands ###
