"""Add procedure_id to attachment for template-level images

Revision ID: eb217417d6d2
Revises: bb285af00e88
Create Date: 2026-05-17 05:47:36.286130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb217417d6d2'
down_revision: Union[str, None] = 'bb285af00e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedure_id', sa.Integer(), nullable=True, comment='Template-level scope: inline images in step instructions / procedure description'))
        batch_op.create_index(batch_op.f('ix_attachment_procedure_id'), ['procedure_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_attachment_procedure_id', 'master_procedure',
            ['procedure_id'], ['id'], ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_attachment_procedure_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attachment_procedure_id'))
        batch_op.drop_column('procedure_id')

    # ### end Alembic commands ###
