"""Credentialed auth: username/password on user; session, API token and passkey tables

Revision ID: f1e2d3c4b5a6
Revises: b3f2c1d4a5e6
Create Date: 2026-06-09

"""

import re

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1e2d3c4b5a6"
down_revision = "b3f2c1d4a5e6"
branch_labels = None
depends_on = None


def _usernameify(raw: str) -> str:
    """Derive a username slug from an email local-part or display name."""
    slug = re.sub(r"[^a-z0-9._-]+", ".", raw.strip().lower()).strip(".")
    return slug[:64] or "user"


def upgrade() -> None:
    bind = op.get_bind()

    # Repair drift from 00d3ac121e5e, which shipped with empty autogenerated
    # stubs: databases that came through the migration path never got
    # user.needs_onboarding even though the model declares it.
    user_columns = {
        row[1] for row in bind.execute(sa.text('PRAGMA table_info("user")')).fetchall()
    }
    if "needs_onboarding" not in user_columns:
        op.add_column(
            "user",
            sa.Column(
                "needs_onboarding", sa.Boolean(), nullable=False, server_default=sa.text("0")
            ),
        )

    # --- user.username / user.password_hash ---
    op.add_column("user", sa.Column("username", sa.String(length=64), nullable=True))
    op.add_column("user", sa.Column("password_hash", sa.String(length=255), nullable=True))

    # Backfill usernames from email local-part, falling back to the display
    # name, deduplicating with numeric suffixes. password_hash stays NULL:
    # migrated accounts set their password on first login.
    bind = op.get_bind()
    rows = bind.execute(sa.text('SELECT id, name, email FROM "user" ORDER BY id')).fetchall()
    taken: set[str] = set()
    for row in rows:
        base = _usernameify((row.email or "").split("@")[0] or row.name or f"user{row.id}")
        candidate = base
        suffix = 2
        while candidate in taken:
            candidate = f"{base}{suffix}"
            suffix += 1
        taken.add(candidate)
        bind.execute(
            sa.text('UPDATE "user" SET username = :u WHERE id = :i'),
            {"u": candidate, "i": row.id},
        )

    with op.batch_alter_table("user") as batch:
        batch.alter_column("username", existing_type=sa.String(length=64), nullable=False)
        batch.create_unique_constraint("uq_user_username", ["username"])
        batch.create_index("ix_user_username", ["username"])

    # --- auth_session ---
    op.create_table(
        "auth_session",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("auth_method", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_auth_session_user_id", "auth_session", ["user_id"])
    op.create_index("ix_auth_session_token_hash", "auth_session", ["token_hash"])

    # --- api_token ---
    op.create_table(
        "api_token",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_api_token_user_id", "api_token", ["user_id"])
    op.create_index("ix_api_token_token_hash", "api_token", ["token_hash"])

    # --- passkey_credential ---
    op.create_table(
        "passkey_credential",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("aaguid", sa.String(length=36), nullable=True),
        sa.Column("transports", sa.String(length=100), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id"),
    )
    op.create_index("ix_passkey_credential_user_id", "passkey_credential", ["user_id"])
    op.create_index("ix_passkey_credential_credential_id", "passkey_credential", ["credential_id"])


def downgrade() -> None:
    op.drop_table("passkey_credential")
    op.drop_table("api_token")
    op.drop_table("auth_session")
    with op.batch_alter_table("user") as batch:
        batch.drop_index("ix_user_username")
        batch.drop_constraint("uq_user_username", type_="unique")
        batch.drop_column("password_hash")
        batch.drop_column("username")
